// script.js is responsible for inserting the HTML containing the data generated by ethereum.js and bitcoin.js
document.onreadystatechange = function (){
  if (document.readyState == 'interactive' ){
    BitcoinDataHandler.init();
    EthereumDataHandler.init();
  }
}
